/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./src/components/widget/alert/BaseAlert.vue')['default']
    BaseDialog: typeof import('./src/components/widget/dialog/BaseDialog.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeaderOld.vue')['default']
    BaseHeaderOld: typeof import('./src/components/BaseHeaderOld.vue')['default']
    BaseSideBar: typeof import('./src/components/aside/BaseSideBar.vue')['default']
    CategoryCard: typeof import('./src/components/widget/card/CategoryCard.vue')['default']
    CategoryForm: typeof import('./src/components/form/CategoryForm.vue')['default']
    CategoryFormDialog: typeof import('./src/components/CategoryFormDialog.vue')['default']
    ChefOrderCard: typeof import('./src/components/widget/card/ChefOrderCard.vue')['default']
    DangerButton: typeof import('./src/components/widget/button/DangerButton.vue')['default']
    DarkButton: typeof import('./src/components/widget/button/DarkButton.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    HeaderComponent: typeof import('./src/components/widget/header/HeaderComponent.vue')['default']
    OrderListTable: typeof import('./src/components/table/OrderListTable.vue')['default']
    PrimaryButton: typeof import('./src/components/widget/button/PrimaryButton.vue')['default']
    ProductCard: typeof import('./src/components/widget/card/ProductCard.vue')['default']
    ProductForm: typeof import('./src/components/form/ProductForm.vue')['default']
    ProductListTable: typeof import('./src/components/table/ProductListTable.vue')['default']
    ProductResOwnerCard: typeof import('./src/components/widget/card/ProductResOwnerCard.vue')['default']
    ResOwnerSideBar: typeof import('./src/components/aside/ResOwnerSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/widget/button/SecondaryButton.vue')['default']
    StaffCard: typeof import('./src/components/widget/card/StaffCard.vue')['default']
    StaffForm: typeof import('./src/components/form/StaffForm.vue')['default']
    StoreForm: typeof import('./src/components/form/StoreForm.vue')['default']
    SummaryComponent: typeof import('./src/components/summary/SummaryComponent.vue')['default']
    TableCard: typeof import('./src/components/widget/card/TableCard.vue')['default']
    TableForm: typeof import('./src/components/form/TableForm.vue')['default']
    UpdateProfileForm: typeof import('./src/components/form/UpdateProfileForm.vue')['default']
    UploadingProgress: typeof import('./src/components/progress/UploadingProgress.vue')['default']
  }
}
