export const PERMISSION_NAME = {
  DASHBOARD: 'DASHBOARD',
  USER: 'USER',
  STORE: 'STORE',
  PRODUCT: 'PRODUCT',
  CATEGORY: 'CATEGORY',
  TABLE: 'TABLE',
  ORDER: 'ORDER',
  RECIPT: 'RECIPT',
  COOK: 'COOK',
  SALE: 'SALE',
  MONEY: 'MONEY',
}
